main: com.redblock6.flytoggle.FlyTogglePlugin
name: FLYTOGGLE
version: '1.1.4'
description: Toggles your fly
author: Redblock6
website: redblock6.com
commands:
    fly:
      description: Toggles your fly ON or OFF
      permission: redblock.fly
      permission-message: You don''t have permission to use this command.
    flytoggle:
      description: The fly toggle help page!
 
permissions:
  redblock.fly:
   description: Allows you to use /fly
