#The 'only players' message, only sent in the console
console_error_message: '&2&lWOAH! &fOnly &aplayers &fcan use this command'

#Flight messages
flying_enabled: '&2&lSUCCESS &fSet flight: &4&lDISABLED &f-> &2&lENABLED'
flying_disabled: '&4&lSUCCESS &fSet flight: &2&lENABLED &f-> &4&lDISABLED'
